/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PonySolution.ui;

/**
 *
 * @author Apostolidis
 */
public class IndexingProcedurePanel extends javax.swing.JPanel {
    private PonyUi ponyUi;
    /**
     * Creates new form IndexingProcedurePanel
     */
    public IndexingProcedurePanel(PonyUi ponyUi) {
        initComponents();
        this.ponyUi = ponyUi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_progressBar = new javax.swing.JProgressBar();
        id_processStatusLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 90));

        id_progressBar.setName(""); // NOI18N
        id_progressBar.setString("");
        id_progressBar.setStringPainted(true);

        id_processStatusLabel.setText("Indexing phase");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id_processStatusLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(id_progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_processStatusLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id_processStatusLabel;
    private javax.swing.JProgressBar id_progressBar;
    // End of variables declaration//GEN-END:variables

    void setProcessStatusMsgLabel(String msg) {
        // TODO: other label for msg
        id_processStatusLabel.setText( id_processStatusLabel.getText() + "  " +  msg);
    }

    void setProcessBar(int percent) {
        id_progressBar.setValue(percent);
        id_progressBar.setString(percent+"%");
    }

    void setProcessStatusLabel(String state) {
        id_processStatusLabel.setText(state);
    }
}
