/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PonySolution.ui;

import PonyDB.DBReader;
import PonySearcher.PageRankInfo;
import java.awt.Desktop;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JComponent.TOOL_TIP_TEXT_KEY;
import javax.swing.JOptionPane;

/**
 *
 * @author Apostolidis
 */
public class SearchEntry extends javax.swing.JPanel {
    private static final int SNIPPET_MAX_LENGTH = 150;
    private static final int DOC_PATH_MAX_LENGTH = 50;
    private static final int RANK_MAX_LENGTH = 7;
    
    PageRankInfo pageRankInfo;
    /**
     * Creates new form SearchEntry
     */
    public SearchEntry(PageRankInfo pageRankInfo) {
        this.pageRankInfo = pageRankInfo;
        initComponents();
        String path = pageRankInfo.getDocumentPath();
        if(path.length()>DOC_PATH_MAX_LENGTH){
            path = ".." + path.substring(path.length()-DOC_PATH_MAX_LENGTH);
        }   
        
        se_documentPath.setText(path);
        double rank = pageRankInfo.getRank();
        if(rank>0.0){
            String prefix = "";
            if(rank<0.01){
                rank*=1000;
                prefix = "*";
            }
            String strRank = rank + "";
            if(strRank.length()>RANK_MAX_LENGTH){
                 strRank = strRank.substring(0, RANK_MAX_LENGTH);
            } 
            se_rank.setText( prefix + strRank );
        }else{
            se_rank.setText( "" );
        }

        StringBuilder snippets = new StringBuilder("<html>");
        for( String snippet : pageRankInfo.getSnippets() ){
            snippets.append(snippet);
            if(snippets.length()>SNIPPET_MAX_LENGTH){
                snippets.append("...");
                break;
            }
        }
        snippets.append("</html>");
        se_snippet.setText(snippets.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        se_documentPath = new javax.swing.JLabel();
        se_rank = new javax.swing.JLabel();
        se_snippet = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(490, 82));
        setPreferredSize(new java.awt.Dimension(490, 82));

        se_documentPath.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        se_documentPath.setForeground(new java.awt.Color(30, 15, 190));
        se_documentPath.setText("Result path");
        se_documentPath.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        se_documentPath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnUrlMouseClick(evt);
            }
        });

        se_rank.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        se_rank.setForeground(new java.awt.Color(0, 102, 33));
        se_rank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        se_rank.setText("Rank");
        se_rank.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        se_snippet.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        se_snippet.setText("Snippet");
        se_snippet.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(se_documentPath, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(se_snippet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(se_rank, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(se_documentPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(se_rank, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(se_snippet, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OnUrlMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnUrlMouseClick
        if(Desktop.isDesktopSupported()){
            try {
                String filePath = pageRankInfo.getDocumentPath();
                File file = new File(filePath);
                Desktop.getDesktop().open(file);
            } catch (IOException ex) {
                Logger.getLogger(SearchEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_OnUrlMouseClick

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel se_documentPath;
    private javax.swing.JLabel se_rank;
    private javax.swing.JLabel se_snippet;
    // End of variables declaration//GEN-END:variables
}
